version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app1:
    build: ./app1
    ports:
      - "8081:8080"
    depends_on:
      - redis
  app2:
    build: ./app2
    ports:
      - "8082:8080"
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
